security:
    encoders:
        App\Entity\Usuario:
            algorithm: bcrypt
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuario
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
    access_control:
         - { path: '^/articulo', roles: [IS_AUTHENTICATED_FULLY, ROLE_ENCARGADO] }
         - { path: '^/proveedor', roles: [IS_AUTHENTICATED_FULLY, ROLE_ENCARGADO] }
         - { path: '^/pedido', roles: [IS_AUTHENTICATED_FULLY, ROLE_ENCARGADO] }
         - { path: '^/articulo', roles: [IS_AUTHENTICATED_FULLY, ROLE_GERENTE] }
         - { path: '^/proveedor', roles: [IS_AUTHENTICATED_FULLY, ROLE_GERENTE] }
         - { path: '^/pedido', roles: [IS_AUTHENTICATED_FULLY, ROLE_GERENTE] }
         - { path: '^/register', roles: ROLE_GERENTE }

