version: '3'
services:
  app:
        image: waynabox/waynabox_php7_server:symfony4v2
        ports:
            - '8000:80'
        environment:
            - SERVER_PROFILE=prod
            - FRONT_HOST=localhost
            - START_PAGE=index.php
        volumes:
            - ./:/var/www/current
  mysql:
        image: mysql:8.0
        restart: on-failure
        environment: 
            MYSQL_ROOT_PASSWORD: mario.1234.
            MYSQL_ROOT_DATABASE: example
            MYSQL_USER: mario
            MYSQL_PASSWORD: mario.1234.
            MYSQL_DATABASE: 'restaurantejmj'
        ports:
            - '3306:3306'
        expose: 
            - '3306'